x = int(input("Enter x coordinate: "))
y = int(input("Enter y coordinate: "))

if(x>0 and y>0): print(f"Point P({x},{y}) is in the first quadrant of the coordinate system.")
if(x<0 and y>0): print(f"Point P({x},{y}) is in the second quadrant of the coordinate system.")
if(x<0 and y<0): print(f"Point P({x},{y}) is in the third quadrant of the coordinate system.")
if(x>0 and y<0): print(f"Point P({x},{y}) is in the fourth quadrant of the coordinate system.")
if(x==0): print(f"Point P({x},{y}) is on the Y Axis")
if(y==0): print(f"Point P({x},{y}) is on the X Axis")
if(y==0 and x==0): print(f"Point P({x},{y}) is in the position (0, 0) of the coordinates system")
